const responseObj = {
  hello: "Hello! How can I assist you today?",
  hi: "Hi there! What can I help you with?",
  hey: "Hey! What's up?",
  "i am not feeling well": "I'm sorry to hear that. Please let me know your symptoms, and I'll try to help you.",
  "not feeling well": "I'm here to help. Please describe your symptoms so I can assist you better.",
  "feeling sick": "I'm sorry you're not feeling well. Can you tell me more about your symptoms?",
  "hello": "Hello! How can I assist you today?",
"hi": "Hi there! What can I help you with?",
"hey": "Hey! What's up?",
"i'm not feeling well": "I'm sorry to hear that. Please let me know your symptoms, and I'll try to help you.",
"not feeling well": "I'm here to help. Please describe your symptoms so I can assist you better.",
"feeling sick": "I'm sorry you're not feeling well. Can you tell me more about your symptoms?",
"feeling unwell": "I'm here to assist you. Please provide details about your symptoms, and I'll do my best to help.",
"having health issues": "I'm here to help you with your health concerns. Please describe your symptoms or issues.",
"suffering from symptoms": "I'm sorry you're experiencing symptoms. Please let me know what you're experiencing so I can assist you.",
"experiencing discomfort": "I'm here to assist you. Can you please tell me what kind of discomfort you're feeling?",
"not feeling myself": "I'm sorry to hear that. Can you describe how you're feeling differently than usual?",
"feeling under the weather": "I'm here to help. Please let me know how you're feeling, and I'll provide assistance.",
"having health problems": "I'm sorry to hear that. Please describe your health problems, and I'll try to provide guidance.",
"having symptoms": "I'm here to assist you. Please describe the symptoms you're experiencing, and I'll do my best to help.",
"having issues": "I am here to help you with any issues you are facing. Please provide", 
  today: new Date().toDateString(),
  time: new Date().toLocaleTimeString(),
  fever: "Fever can be a sign of an underlying infection or illness. It's important to monitor your temperature and consult with a healthcare professional if it persists or if you experience other symptoms.",
  cough: "A cough can be caused by various factors such as respiratory infections, allergies, or environmental irritants. If your cough is persistent or accompanied by other symptoms, it's advisable to seek medical advice.",
  headache: "Headaches can have many causes, including stress, dehydration, tension, or underlying medical conditions. If you experience severe or frequent headaches, it's important to consult with a doctor for proper evaluation.",
  fatigue: "Fatigue can result from a variety of factors, including lack of sleep, stress, or medical conditions such as anemia or thyroid disorders. It's important to address the underlying cause of fatigue with the help of a healthcare professional.",
  nausea: "Nausea can be caused by many factors, including infections, motion sickness, pregnancy, or digestive issues. If you experience persistent or severe nausea, it's important to consult with a doctor.",
  "sore throat": "A sore throat can be a symptom of various conditions, including viral or bacterial infections, allergies, or irritants. Gargling with warm salt water and staying hydrated may provide relief, but if it persists or is severe, seek medical advice.",
  "stomach ache": "Stomach aches can be caused by many factors, including indigestion, gastritis, food poisoning, or gastrointestinal infections. If you experience persistent or severe stomach pain, it's important to consult with a doctor.",
  diarrhea: "Diarrhea can be a result of infections, food poisoning, dietary changes, or underlying medical conditions. It's important to stay hydrated and avoid certain foods until symptoms improve. If diarrhea persists, seek medical advice.",
  constipation: "Constipation can be caused by dehydration, lack of fiber in the diet, or underlying medical conditions. Increasing fiber intake, drinking plenty of water, and staying physically active may help. If constipation persists, consult with a doctor.",
  rash: "A rash can be caused by various factors, including allergic reactions, infections, or skin conditions such as eczema or psoriasis. Avoid scratching the rash and keep the affected area clean. If it worsens or spreads, seek medical advice.",
  "difficulty breathing": "Difficulty breathing can be a serious symptom that requires immediate medical attention. It can be caused by asthma, pneumonia, allergies, or other respiratory conditions. Seek emergency help if you experience sudden or severe difficulty breathing.",
  "chest pain": "Chest pain can have many causes, including heart problems, lung conditions, or musculoskeletal issues. If you experience chest pain, especially if it's severe or accompanied by other symptoms such as shortness of breath or dizziness, seek emergency medical help.",
  dizziness: "Dizziness can be caused by various factors, including low blood pressure, dehydration, inner ear problems, or neurological conditions. If you experience persistent or severe dizziness, lie down and seek medical advice.",
  weakness: "Weakness can result from various factors, including lack of sleep, nutritional deficiencies, or underlying medical conditions such as anemia or thyroid disorders. If weakness persists or is accompanied by other symptoms, consult with a doctor.",
  "loss of appetite": "Loss of appetite can be caused by various factors, including illness, medications, or emotional stress. Try eating small, frequent meals and staying hydrated. If loss of appetite persists, seek medical advice.",
  "muscle pain": "Muscle pain can be caused by overuse, injury, or underlying medical conditions such as fibromyalgia or autoimmune disorders. Rest, gentle stretching, and over-the-counter pain relievers may help. If pain is severe or persistent, consult with a doctor.",
  // Add more health-related queries and responses here
};

// Example usage:
console.log(responseObj["fever"]); // Output: "Fever can be a sign of an underlying infection or illness. It's important to monitor your temperature and consult with a healthcare professional if it persists or if you experience other symptoms."
console.log(responseObj["not feeling well"]); // Output: "I'm here to help. Please describe your symptoms so I can assist you better."
